# -*- coding: utf-8 -*-
"""7.동전확류분포.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12hQH10X2dANzgkC-8AcG7eFKqiVJwJkN
"""

import sys
import math
print(sys.version)
print(math.factorial(5))

def combination_count(n,r):
  return math.factorial(n) //(math.factorial(n - r)*math.factorial(r) )

print("동전 한갸를 n번 던져서 뒷면이 나올 확률은 ? \n")

n=0
print("던지는 횟수를 입력하세요.")
n = int(input())

total_n= pow(2,n)
print(total_n)

avg=0.0
for x in range(n+1):
  P =  combination_count(n,x)/ total_n
  avg += x * P
  print("P(",x, ")=", P)
print("average =", avg)

for x in range(n+1):
  P = combination_count(n,x)/ total_n
  var = (x- avg)*(x-avg) * P
print("variance=", var)