# -*- coding: utf-8 -*-
"""EMPLOYMENT_MOV_AVG_FILTER(1_2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbLIBjCxODptcI5sJL2ru9d7Dae9gZtx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("/content/drive/MyDrive/data/EEMP.csv", encoding='euc-kr')

print(data)

def EMP(i):
    z = data['P'][i]
    return z

#인덱스는 0에서 부터 시작하기 때문에 n-1 을 해야 한다.
def mov_avg_filter(x_n, x_meas):
  n = len(x_n)
  for i in range(n-1):
    x_n[i] = x_n[i + 1]
    x_n[n-1] = x_meas
    x_avg = np.mean(x_n)

  return x_avg, x_n

len(data)

n = 10
n_samples = 96
time_end = 10

dt = time_end / n_samples
time = np.arange(0, time_end, dt)
x_meas_save = np.zeros(n_samples)
x_avg_save = np.zeros(n_samples)

print(time)
print(x_meas_save)
print(x_avg_save)

for i in range(n_samples):
  x_meas = EMP(i)
  if i == 0:
    x_avg, x_n = x_meas, x_meas * np.ones(n) # x_meas * np.ones(n)뭐가 나오는지 확인하세요
  else:
   x_avg, x_n = mov_avg_filter(x_n, x_meas)

   x_meas_save[i] = x_meas
   x_avg_save[i] = x_avg

plt.plot(time, x_meas_save, 'r*', label='EMP')
plt.plot(time, x_avg_save, 'b-', label='Low-pass Filter')
plt.legend(loc='upper left')
plt.title('Measured Altitudes v.s. LPF Values')
plt.xlabel('Time')
plt.ylabel('Altitude WoW')
plt.savefig('/content/png')