# -*- coding: utf-8 -*-
"""Missinf data 처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFCDWFKN1tqFAbeAQ0VTfXSu8vdVS8R4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def linear_interploation_2D(x1, y1,z1, x2, y2, z2, x3, y3, z3, x4, y4, z4, input_x, input_y):
  
  h1    = (input_y- y1)/(y2-y1)
  h2    = (y2 - input_y)/(y2-y1)
  M     = h1 * z2 + h2 * z1
  print("h1: ",h1, "h2: ",h2, "M : ",M)

  h3    = (input_y - y3)/(y4-y3)
  h4    = (y4 - input_y)/(y4-y3)
  N     = h4 * z3 + h3 * z4
  print("h3: ",h3, "h4: ",h4, "N : ",N)

  w1   = (input_x - x1) / (x3-x1)
  w2   = (x3 - input_x) / (x3-x1)
  P    = M*w2 + N*w1
  print("w1: ",w1, "w2: ",w2, "P : ",P)

  return P

linear_interploation_2D(0,0,2,  0,1,4, 1,0,3, 1,1,0, 0,1)

X = [0, 2, 4, 6 ]
Y = [0, 2, 4, 6]
Z = [ [1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12],
      [13, 14, 15, 16] ]

print(X[1])
print(Z[3][2])

def find_x_index(X, input_x): 
  for i in range(0, len(X)-1):
    if((X[i]<=input_x)&(X[i+1]>input_x)):
      x_min_index = i
      x_max_index = i+1
      print(x_min_index ,"~", x_max_index)
  return x_min_index, x_max_index 

def find_y_index(Y, input_y): 
  for i in range(0, len(Y)-1):
    if((Y[i]<=input_y)&(Y[i+1]>input_y)):
      y_min_index = i
      y_max_index = i+1
      print(y_min_index ,"~", y_max_index)
  return y_min_index, y_max_index 

xmin_index, xmax_index = find_x_index(X, input_x)
ymin_index, ymax_index = find_y_index(Y, input_y)

input_x = 2
input_y = 2
xmin_index, xmax_index = find_x_index(X, input_x)
ymin_index, ymax_index = find_y_index(Y, input_y)

input_x = 2.2
input_y = 4.3
xmin_index, xmax_index = find_x_index(X, input_x)
ymin_index, ymax_index = find_y_index(Y, input_y)

data = linear_interploation_2D(
   X[xmin_index], Y[ymin_index], Z[xmin_index][ymin_index], 
   X[xmin_index], Y[ymax_index], Z[xmin_index][ymax_index],
   X[xmax_index], Y[ymin_index], Z[xmax_index][ymin_index],
   X[xmax_index], Y[ymax_index], Z[xmax_index][ymax_index],
   input_x, input_y)

print(data)