# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19QHm2jeBiI35KQPyRwkBGFSHg19LGD-8
"""

import matplotlib.pyplot as plt
import numpy as np

#이항계수 파스칼의 삼각형
def bicoeff(n):
    l = [1]
    for _ in range(n):
        l = [a + b for a, b in zip(l + [0], [0] + l)]
    return l

#이항분포
def bidist2(n, p):
    q = 1 - p
    coeff = bicoeff(n)
    dist = np.array([coeff[k] * (p ** k) * (q ** (n - k)) for k in range(n + 1)])
    return dist


def show_plot(p=1/6):
    
    n1 = 10
    n2 = 20
    n3 = 40
    n4 = 80
    
    plt.grid(True)
    plt.plot(bidist2(n1, p), label= r'B(10,1/6)')
    plt.plot(bidist2(n2, p), label= r'B(20,1/6)')
    plt.plot(bidist2(n3, p), label= r'B(40,1/6)')
    plt.plot(bidist2(n4, p), label= r'B(80,1/6)')

    plt.axis([0, 30, 0, 0.35]) 

    plt.title("Binomial Distribution $ B(N, 1/6)")
    plt.xlabel('x')
    plt.ylabel('f(x)')
    plt.legend(bbox_to_anchor=(1.0, -0.2))
    plt.show()
    plt.show()

show_plot()